# Generated by Django 5.0.6 on 2024-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0002_alter_todo_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
